# Generated by Django 5.2.3 on 2025-07-12 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_staff_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=50, unique=True)),
                ('create_by', models.CharField(max_length=50)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('update_by', models.CharField(max_length=50)),
                ('update_at', models.DateField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='O', max_length=1)),
                ('dateofbirth', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('create_by', models.CharField(max_length=50)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('update_by', models.CharField(max_length=50)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.subject')),
            ],
        ),
    ]
