# Generated by Django 5.2.3 on 2025-07-12 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_subject_create_at_alter_subject_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
