# Generated by Django 5.2.3 on 2025-07-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_subject_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='update_at',
            field=models.DateField(),
        ),
    ]
