# Generated by Django 5.2.3 on 2025-07-12 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_alter_subject_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='create_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.staff'),
        ),
    ]
